site_name: ""
theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - search.highlight
    - toc.follow
    - content.code.copy
    - navigation.collapse
  palette:
    - scheme: default
      primary: custom
      accent: pink
  logo: assets/logo.png
  favicon: assets/favicon.png
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Set the homepage to getting-started
docs_dir: docs
use_directory_urls: true
strict: true

nav:
  - "": index.md
  - Getting Started:
      - Overview: getting-started/index.md
  - Concepts & Components:
      - Overview: core-concepts/index.md
      - Document Loaders: 
        - Overview: core-concepts/document-loaders/index.md
        - Tesseract: core-concepts/document-loaders/tesseract.md
        - Azure Form: core-concepts/document-loaders/azure-form.md
      - LLM Integration: 
        - Overview: core-concepts/llm-integration/index.md
        - Models: core-concepts/llm-integration/models.md
      - Contracts: 
        - Overview: core-concepts/contracts/index.md
        - Basic Usage: core-concepts/contracts/basic-usage.md
      - Extractors: 
        - Overview: core-concepts/extractors/index.md
        - Configuration: core-concepts/extractors/configuration.md
  - Examples:
      - Overview: examples/index.md
      - Basic Examples: examples/basic-examples.md
      - Advanced Examples: examples/advanced-examples.md

# Repository
repo_name: extract_thinker
repo_url: https://github.com/enoch3712/ExtractThinker
edit_uri: ""

# Header link
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/enoch3712/ExtractThinker
      name: Extract Thinker on GitHub

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
      toc_depth: 3

extra_css:
  - stylesheets/extra.css